# Generated by Django 2.2.3 on 2020-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_author', models.CharField(max_length=25)),
                ('article_body', models.TextField()),
                ('article_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
